### ISSUE TITLE
Setup does not support python3

### ISSUE THREAD

**Issue by danielguardicore** [six519/PastebinPython#3]
When installing with Python 3.6.2 on Windows, pip version 9.0.1, I receive the following error message.
```
Collecting pastebin_python
  Using cached pastebin_python-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):ed 'pastebin'
      File "<string>", line 1, in <module>
      File "C:\Users\\AppData\Local\Temp\pip-build-_6tbxdhh\pastebin-python\setup.py", line 1, in <module>python setup.py egg_info" failed with error code 1 in C:\Users\\AppData\Local\Temp\pip-b
        import pastebin_python
      File "C:\Users\\AppData\Local\Temp\pip-build-_6tbxdhh\pastebin-python\pastebin_python\__init__.py", line 6, in <module>
        from pastebin import PastebinPython
    ModuleNotFoundError: No module named 'pastebin'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\\AppData\Local\Temp\pip-build-_6tbxdhh\pastebin-python\
```

Python 2 pip works

**Comment by six519** [comment]
Hello Daniel,

Currently, Python 3 is not supported.

**Comment by JazulatorEmu** [comment]
Hu

**Comment by kiraware** [comment]
Hello everyone, i just want to tell you that i create an asynchronous Pastebin.com API wrapper called paspybin. The code is well written, fully tested, and has [good documentation](https://paspybin.readthedocs.io/en/latest/). If you are interested with the new Pastebin API wrapper that i create, you can check it out at https://github.com/kiraware/paspybin. 

Thank you
